processing:
  use_animated_captions: true
  shorts_dir: "shorts"
  videos_dir: "videos"
  crop_bottom_percent: 0.0
  min_video_dimension_px: 100
  log_transcription_preview_len: 200

llm:
  model_name: "gemini-2.5-flash"
  temperature_highlights: 0.2
  temperature_metadata: 1.0
  max_attempts_highlights: 3
  max_attempts_metadata: 3
  highlight_min_sec: 29
  highlight_max_sec: 61
  max_highlights: 20

paths:
  face_cascade: "haarcascade_frontalface_default.xml"
  font: "fonts/Montserrat-Bold.ttf"

ffmpeg:
  gpu_preset: "p5"
  cpu_preset: "veryfast"
  cpu_codec: "libx264"

video_processing:
  temp_audio_filename: "audio.wav"
  crop_height: 1080
  crop_width: 608
  face_detection_sample_rate: 25

captions:
  font_name: "Montserrat"
  font_size_ratio: 25
  outline_ratio: 10
  shadow_ratio: 2
  margin_v_ratio: 15