processing:
  use_animated_captions: true
  shorts_dir: "shorts"
  videos_dir: "videos"
  crop_bottom_percent: 0.0
  min_video_dimension_px: 100
  log_transcription_preview_len: 200

llm:
  model_name: "gemini-2.5-flash"
  temperature_highlights: 0.2
  temperature_metadata: 1.0
  max_attempts_highlights: 3
  max_attempts_metadata: 3
  highlight_min_sec: 29
  highlight_max_sec: 61
  max_highlights: 20

logging:
  log_dir: "logs"
  log_level: "INFO"
  enable_performance_monitoring: true
  enable_gpu_monitoring: true
  enable_progress_bars: true
  log_rotation_max_bytes: 10485760  # 10MB
  log_rotation_backup_count: 5
  performance_log_max_bytes: 5242880  # 5MB
  performance_log_backup_count: 3
  enable_system_info_logging: true
  gpu_priority_mode: true
  resource_monitoring_interval: 1.0  # seconds