processing:
  use_animated_captions: true
  shorts_dir: "shorts"
  videos_dir: "videos"
  crop_bottom_percent: 0.0
  min_video_dimension_px: 100
  log_transcription_preview_len: 200

llm:
  model_name: "gemini-2.5-flash"
  temperature_highlights: 0.2
  temperature_metadata: 1.0
  max_attempts_highlights: 3
  max_attempts_metadata: 3
  highlight_min_sec: 29
  highlight_max_sec: 61
  max_highlights: 20

logging:
  # Основные настройки логирования
  log_dir: "logs"
  log_level: "INFO"
  enable_console_logging: true
  enable_file_logging: true

  # Настройки ротации логов
  log_rotation_max_bytes: 10485760  # 10MB
  log_rotation_backup_count: 5
  log_rotation_when: "midnight"  # daily rotation at midnight
  log_compression: false

  # Отдельные логгеры для разных типов сообщений
  enable_main_logger: true
  enable_performance_logger: true
  enable_error_logger: true
  enable_debug_logger: false

  # Настройки производительности
  enable_performance_monitoring: true
  performance_log_max_bytes: 5242880  # 5MB
  performance_log_backup_count: 3
  performance_monitoring_interval: 0.5  # seconds

  # Настройки GPU мониторинга
  enable_gpu_monitoring: true
  gpu_priority_mode: true
  gpu_memory_threshold: 0.9  # 90% memory usage warning
  gpu_temperature_threshold: 80  # Celsius

  # Настройки CPU и памяти
  enable_cpu_monitoring: true
  enable_memory_monitoring: true
  memory_threshold: 0.85  # 85% memory usage warning
  cpu_threshold: 90.0  # 90% CPU usage warning

  # Настройки прогресс-баров
  enable_progress_bars: true
  progress_bar_update_interval: 0.1  # seconds

  # Системная информация
  enable_system_info_logging: true
  system_info_log_interval: 3600  # 1 hour in seconds

  # Асинхронная обработка
  enable_async_logging: true
  log_queue_size: 1000
  log_worker_threads: 2

  # Форматирование логов
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_date_format: "%Y-%m-%d %H:%M:%S"
  enable_colors: true

  # Фильтры логирования
  log_filters:
    - "urllib3.connectionpool"  # Filter noisy HTTP logs
    - "PIL.PngImagePlugin"      # Filter PIL debug logs

  # Настройки для разных сред
  development_mode: false
  enable_detailed_tracing: false
  enable_function_call_logging: false

  # Ресурсный мониторинг
  resource_monitoring_interval: 1.0  # seconds
  enable_resource_monitoring: true
  enable_resource_alerts: true
  alert_threshold_duration: 30.0  # seconds for long operations