# --- Paths & processing hints (comments only, safe to keep as-is) ---
# Все пути теперь резолвятся относительно paths.base_dir.
# Для Colab/контейнеров можно указать base_dir как рабочую директорию окружения;
# fonts_dir и прочие каталоги будут резолвиться относительно base_dir.
#
# Примерные значения по умолчанию (РАЗКОММЕНТИРУЙТЕ при необходимости переопределения):
# paths:
#   base_dir: .
#   fonts_dir: fonts
# processing:
#   transcriptions_dir: "transcriptions"  # экспорт .txt/.json/.srt/.vtt
#   shorts_dir: "shorts"                   # каталог итоговых шортов
processing:
  use_animated_captions: true
  shorts_dir: "shorts"
  videos_dir: "videos"
  transcriptions_dir: "transcriptions"
  crop_bottom_percent: 0.0
  min_video_dimension_px: 100
  log_transcription_preview_len: 200
  crop_mode: "70_percent_blur"  # "average_face" or "70_percent_blur"

llm:
  model_name: "gemini-2.5-flash"
  temperature_highlights: 0.2
  temperature_metadata: 1.0
  max_attempts_highlights: 3
  max_attempts_metadata: 3
  highlight_min_sec: 29
  highlight_max_sec: 61
  max_highlights: 20

# Настройки режима "фильм"
film_mode:
  enabled: true
  generate_shorts: true  # ВКЛЮЧЕНА генерация шортов
  combo_duration: [10, 20]  # секунды для COMBO моментов
  single_duration: [30, 60]  # секунды для SINGLE моментов
  max_moments: 30  # максимальное количество моментов для анализа (монолитный режим)
  pause_threshold: 0.7  # порог для определения длинных пауз (секунды)
  filler_words: ["э-э", "м-м", "ну", "эээ", "гм", "кхм"]  # слова-заполнители для обрезки

  # Film Mode v2: Оконный LLM-конвейер для длинных фильмов
  window_minutes: 12  # размер окна в минутах
  window_overlap_minutes: 3  # перекрытие окон в минутах
  max_moments_per_window: 12  # максимум моментов на окно

  # Цели генерации и лимиты
  target_shorts_count: 30  # целевое количество финальных шортов
  generator_top_k: 30  # сколько топ моментов брать для генерации

  # Дедупликация и диверсификация
  dedupe_iou_threshold: 0.5  # порог IoU для дедупликации по времени
  diversity_bucket_minutes: 5  # размер бакетов для диверсификации по таймлайну
  min_combo_segments: 2  # минимум суб-сегментов в COMBO
  max_combo_segments: 4  # максимум суб-сегментов в COMBO

  # Весовые коэффициенты для ранжирования моментов
  ranking_weights:
    emotional_peaks: 0.20      # Эмоциональные пики и переломы статуса
    conflict_escalation: 0.18  # Конфликт и эскалация
    punchlines_wit: 0.16       # Панчлайны и остроумие
    quotability_memes: 0.14    # Цитатность/мемность
    stakes_goals: 0.12         # Ставки и цель
    hooks_cliffhangers: 0.10   # Крючки/клиффхэнгеры
    visual_penalty: -0.10      # Штраф за визуальную зависимость
    pace_score: 0.08           # Плотность речи (слова/сек)
    silence_penalty: -0.08     # Наказание за долю длинных пауз
    diversity_bonus: 0.05      # Бонус за диверсификацию

  # Настройки ранжирования и fallback
  ranking:
    min_quality_threshold: 0.3
    soft_min_quality: 0.2
    allow_fallback: true
    fallback_top_n: 15
    max_best_moments: 30

  # Настройки LLM для анализа фильма
  llm:
    model: "gemini-2.5-flash"
    temperature: 0.3
    max_attempts: 3

logging:
  # Основные настройки логирования
  log_dir: "logs"
  log_level: "INFO"
  enable_console_logging: true
  enable_file_logging: true

  # Настройки ротации логов
  log_rotation_max_bytes: 10485760  # 10MB
  log_rotation_backup_count: 5
  log_rotation_when: "midnight"  # daily rotation at midnight
  log_compression: false

  # Отдельные логгеры для разных типов сообщений
  enable_main_logger: true
  enable_performance_logger: true
  enable_error_logger: true
  enable_debug_logger: false

  # Настройки производительности
  enable_performance_monitoring: true
  performance_log_max_bytes: 5242880  # 5MB
  performance_log_backup_count: 3
  performance_monitoring_interval: 0.5  # seconds

  # Настройки GPU мониторинга
  enable_gpu_monitoring: true
  gpu_priority_mode: true
  gpu_memory_threshold: 0.9  # 90% memory usage warning
  gpu_temperature_threshold: 80  # Celsius

  # Настройки CPU и памяти
  enable_cpu_monitoring: true
  enable_memory_monitoring: true
  memory_threshold: 0.85  # 85% memory usage warning
  cpu_threshold: 90.0  # 90% CPU usage warning

  # Настройки прогресс-баров
  enable_progress_bars: true
  progress_bar_update_interval: 0.1  # seconds

  # Системная информация
  enable_system_info_logging: true
  system_info_log_interval: 3600  # 1 hour in seconds

  # Асинхронная обработка
  enable_async_logging: true
  log_queue_size: 1000
  log_worker_threads: 2

  # Форматирование логов
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_date_format: "%Y-%m-%d %H:%M:%S"
  enable_colors: true

  # Фильтры логирования
  log_filters:
    - "urllib3.connectionpool"  # Filter noisy HTTP logs
    - "PIL.PngImagePlugin"      # Filter PIL debug logs

  # Настройки для разных сред
  development_mode: false
  enable_detailed_tracing: false
  enable_function_call_logging: false

  # Ресурсный мониторинг
  resource_monitoring_interval: 1.0  # seconds
  enable_resource_alerts: true
  alert_threshold_duration: 30.0  # seconds for long operations
paths:
  base_dir: .
  fonts_dir: fonts
captions:
  font_size_px: 38
  letter_spacing_px: 1.5
  line_height: 1.3
  base_color: "#FFFFFF"
  strip_punctuation: true
  align_to_audio: true
  fade_in_seconds: 0.15
  fade_out_seconds: 0.12
  shadow:
    x_px: 2
    y_px: 2
    blur_px: 1
    color: "#00000080"
  accent_palette:
    urgency: "#FFD400"
    drama: "#FF3B30"
    positive: "#34C759"
  animate:
    type: "slide-up"         # возможные: "pop-in" | "slide-up"
    duration_s: 0.35         # диапазон 0.2–0.5
    easing: "easeOutCubic"
    per_word_stagger_ms: 120
  position:
    mode: "safe_bottom"      # возможные: "safe_bottom" | "center"
    bottom_offset_pct: 22    # 20–28% рекомендовано, по умолчанию 22
    center_offset_pct: 12
    boundary_padding_px: 10
  emoji:
    enabled: false
    max_per_short: 2
    style: "shiny"           # возможные: "shiny" | "pulse" | "none"